linters:
  enable:
    - revive # golint ha sido deprecado, revive es su reemplazo
    - govet
    - staticcheck

linters-settings:
  staticcheck:
    checks:
      - all
      - '-SA1000' # disable the rule SA1000 - Invalid regular expression
      - '-SA1004' # disable the rule SA1004 - Suspiciously small untyped constant in time.Sleep
